apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: /afk-no
      - op: add
        path: "/spec/resources"
        value:
          limits:
            memory: "0.8Gi"
          requests:
            memory: "0.5Gi"
    target:
      kind: FLAISSso
      name: fint-kontroll-sso
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: /afk-no
    target:
      kind: Application
      name: fint-kontroll-frontend
  - patch: |-
      - op: replace
        path: "/spec/prometheus/path"
        value: /afk-no/metrics
    target:
      kind: Application
      name: fint-kontroll-frontend
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: BASE_PATH
          value: /afk-no
      - op: add
        path: "/spec/env/-"
        value:
          name: USER_API_URL
          value: http://fint-kontroll-user-catalog:8080
      - op: add
        path: "/spec/env/-"
        value:
          name: ROLE_API_URL
          value: http://fint-kontroll-role-catalog:8080
      - op: add
        path: "/spec/env/-"
        value:
          name: RESOURCE_API_URL
          value: http://fint-kontroll-resource-catalog:8080
      - op: add
        path: "/spec/env/-"
        value:
          name: ORG_UNIT_API_URL
          value: http://fint-kontroll-orgunit-catalog:8080
      - op: add
        path: "/spec/env/-"
        value:
          name: ASSIGNMENT_API_URL
          value: http://fint-kontroll-assignment-catalog:8080
      - op: add
        path: "/spec/env/-"
        value:
          name: ACCESS_MANAGEMENT_API_URL
          value: http://fint-kontroll-access-mngmnt-catalog:8080
      - op: add
        path: "/spec/env/-"
        value:
          name: LOG_LEVEL
          value: info
    target:
      kind: Application
      name: fint-kontroll-frontend
  - patch: |-
      - op: replace
        path: "/spec/image"
        value: ghcr.io/fintlabs/fint-kontroll-frontend-afk-no-api
    target:
      kind: Application
      name: fint-kontroll-frontend