apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: /beta/fintlabs-no
    target:
      kind: FLAISSso
      name: fint-kontroll-sso
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: /beta/fintlabs-no
    target:
      kind: Application
      name: fint-kontroll-frontend
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: BASE_PATH
          value: /beta/fintlabs-no
    target:
      kind: Application
      name: fint-kontroll-frontend