// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/bruker/:id/ressurs/:resourceId/org/:orgId/tildel": {
    params: {
      "id": string;
      "resourceId": string;
      "orgId": string;
    };
  };
  "/tjeneste-admin/rediger/org-enheter/ressurs/:id": {
    params: {
      "id": string;
    };
  };
  "/tjeneste-admin/opprett-ny-applikasjonsressurs": {
    params: {};
  };
  "/brukere/:id/tildelinger/:assignmentRef/slett": {
    params: {
      "id": string;
      "assignmentRef": string;
    };
  };
  "/bruker/:id/org/:orgId/ny-tildeling": {
    params: {
      "id": string;
      "orgId": string;
    };
  };
  "/innstillinger/applikasjonskategori": {
    params: {};
  };
  "/innstillinger/applikasjonskategori/:id?/rediger": {
    params: {
      "id"?: string;
    };
  };
  "/innstillinger/applikasjonskategori/:id/slett": {
    params: {
      "id": string;
    };
  };
  "/ressurs-admin/opprett-ny-tildeling": {
    params: {};
  };
  "/tjeneste-admin/rediger/ressurs/:id": {
    params: {
      "id": string;
    };
  };
  "/tjeneste-admin/ressurser/:id/slett": {
    params: {
      "id": string;
    };
  };
  "/innstillinger/haandhevingstyper": {
    params: {};
  };
  "/innstillinger/haandhevingstyper/:id/rediger": {
    params: {
      "id": string;
    };
  };
  "/tjeneste-admin/ressurser": {
    params: {};
  };
  "/ressurs-admin/administrer/:id": {
    params: {
      "id": string;
    };
  };
  "/innstillinger/lisensmodeller": {
    params: {};
  };
  "/innstillinger/lisensmodeller/:id?/rediger": {
    params: {
      "id"?: string;
    };
  };
  "/innstillinger/lisensmodeller/:id/slett": {
    params: {
      "id": string;
    };
  };
  "/tjeneste-admin/ressurs/:id": {
    params: {
      "id": string;
    };
  };
  "/innstillinger/brukertyper": {
    params: {};
  };
  "/innstillinger/brukertyper/:id/rediger": {
    params: {
      "id": string;
    };
  };
  "/ressurs/:id/ny-tildeling": {
    params: {
      "id": string;
    };
  };
  "/ressurs/:id/ny-tildeling/brukere": {
    params: {
      "id": string;
    };
  };
  "/ressurs/:id/ny-tildeling/brukere/:userId/org/:orgId/tildel": {
    params: {
      "id": string;
      "userId": string;
      "orgId": string;
    };
  };
  "/ressurs/:id/ny-tildeling/grupper": {
    params: {
      "id": string;
    };
  };
  "/ressurs/:id/ny-tildeling/grupper/:roleId/org/:orgId/tildel": {
    params: {
      "id": string;
      "roleId": string;
      "orgId": string;
    };
  };
  "/gruppe/:id/ny-tildeling": {
    params: {
      "id": string;
    };
  };
  "/gruppe/:id/ny-tildeling/ressurs/:resourceId/org/:orgId/tildel": {
    params: {
      "id": string;
      "resourceId": string;
      "orgId": string;
    };
  };
  "/brukere/:id/org/:orgId": {
    params: {
      "id": string;
      "orgId": string;
    };
  };
  "/innstillinger": {
    params: {};
  };
  "/ressurs-admin": {
    params: {};
  };
  "/ressurser": {
    params: {};
  };
  "/brukere": {
    params: {};
  };
  "/grupper": {
    params: {};
  };
  "/ressurser/:id": {
    params: {
      "id": string;
    };
  };
  "/ressurser/:id/bruker-tildelinger": {
    params: {
      "id": string;
    };
  };
  "/ressurser/:id/bruker-tildelinger/:assignmentRef/slett": {
    params: {
      "id": string;
      "assignmentRef": string;
    };
  };
  "/ressurser/:id/gruppe-tildelinger": {
    params: {
      "id": string;
    };
  };
  "/ressurser/:id/gruppe-tildelinger/:assignmentRef/slett": {
    params: {
      "id": string;
      "assignmentRef": string;
    };
  };
  "/system-admin": {
    params: {};
  };
  "/system-admin/knytt-rettigheter-til-rolle": {
    params: {};
  };
  "/system-admin/knytt-rettigheter-til-rolle/:id": {
    params: {
      "id": string;
    };
  };
  "/system-admin/definer-rolle": {
    params: {};
  };
  "/system-admin/definer-rolle/:id": {
    params: {
      "id": string;
    };
  };
  "/system-admin/menystyring": {
    params: {};
  };
  "/system-admin/menystyring/:id": {
    params: {
      "id": string;
    };
  };
  "/grupper/:id": {
    params: {
      "id": string;
    };
  };
  "/grupper/:id/tildelinger": {
    params: {
      "id": string;
    };
  };
  "/grupper/:id/tildelinger/:assignmentRef/slett": {
    params: {
      "id": string;
      "assignmentRef": string;
    };
  };
  "/grupper/:id/medlemmer": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/bruker/:id/ressurs/:resourceId/org/:orgId/tildel" | "/tjeneste-admin/rediger/org-enheter/ressurs/:id" | "/tjeneste-admin/opprett-ny-applikasjonsressurs" | "/brukere/:id/tildelinger/:assignmentRef/slett" | "/bruker/:id/org/:orgId/ny-tildeling" | "/innstillinger/applikasjonskategori" | "/innstillinger/applikasjonskategori/:id?/rediger" | "/innstillinger/applikasjonskategori/:id/slett" | "/ressurs-admin/opprett-ny-tildeling" | "/tjeneste-admin/rediger/ressurs/:id" | "/tjeneste-admin/ressurser/:id/slett" | "/innstillinger/haandhevingstyper" | "/innstillinger/haandhevingstyper/:id/rediger" | "/tjeneste-admin/ressurser" | "/ressurs-admin/administrer/:id" | "/innstillinger/lisensmodeller" | "/innstillinger/lisensmodeller/:id?/rediger" | "/innstillinger/lisensmodeller/:id/slett" | "/tjeneste-admin/ressurs/:id" | "/innstillinger/brukertyper" | "/innstillinger/brukertyper/:id/rediger" | "/ressurs/:id/ny-tildeling" | "/ressurs/:id/ny-tildeling/brukere" | "/ressurs/:id/ny-tildeling/brukere/:userId/org/:orgId/tildel" | "/ressurs/:id/ny-tildeling/grupper" | "/ressurs/:id/ny-tildeling/grupper/:roleId/org/:orgId/tildel" | "/gruppe/:id/ny-tildeling" | "/gruppe/:id/ny-tildeling/ressurs/:resourceId/org/:orgId/tildel" | "/brukere/:id/org/:orgId" | "/innstillinger" | "/ressurs-admin" | "/ressurser" | "/brukere" | "/grupper" | "/ressurser/:id" | "/ressurser/:id/bruker-tildelinger" | "/ressurser/:id/bruker-tildelinger/:assignmentRef/slett" | "/ressurser/:id/gruppe-tildelinger" | "/ressurser/:id/gruppe-tildelinger/:assignmentRef/slett" | "/system-admin" | "/system-admin/knytt-rettigheter-til-rolle" | "/system-admin/knytt-rettigheter-til-rolle/:id" | "/system-admin/definer-rolle" | "/system-admin/definer-rolle/:id" | "/system-admin/menystyring" | "/system-admin/menystyring/:id" | "/grupper/:id" | "/grupper/:id/tildelinger" | "/grupper/:id/tildelinger/:assignmentRef/slett" | "/grupper/:id/medlemmer";
  };
  "routes/bruker.$id.ressurs.$resourceId.org.$orgId.tildel.tsx": {
    id: "routes/bruker.$id.ressurs.$resourceId.org.$orgId.tildel";
    page: "/bruker/:id/ressurs/:resourceId/org/:orgId/tildel";
  };
  "routes/tjeneste-admin.rediger.org-enheter.ressurs.$id.tsx": {
    id: "routes/tjeneste-admin.rediger.org-enheter.ressurs.$id";
    page: "/tjeneste-admin/rediger/org-enheter/ressurs/:id";
  };
  "routes/tjeneste-admin.opprett-ny-applikasjonsressurs.tsx": {
    id: "routes/tjeneste-admin.opprett-ny-applikasjonsressurs";
    page: "/tjeneste-admin/opprett-ny-applikasjonsressurs";
  };
  "routes/brukere.$id.tildelinger.$assignmentRef.slett.tsx": {
    id: "routes/brukere.$id.tildelinger.$assignmentRef.slett";
    page: "/brukere/:id/tildelinger/:assignmentRef/slett";
  };
  "routes/bruker.$id.org.$orgId.ny-tildeling.tsx": {
    id: "routes/bruker.$id.org.$orgId.ny-tildeling";
    page: "/bruker/:id/org/:orgId/ny-tildeling";
  };
  "routes/innstillinger.applikasjonskategori.tsx": {
    id: "routes/innstillinger.applikasjonskategori";
    page: "/innstillinger/applikasjonskategori" | "/innstillinger/applikasjonskategori/:id?/rediger" | "/innstillinger/applikasjonskategori/:id/slett";
  };
  "routes/innstillinger.applikasjonskategori.($id).rediger.tsx": {
    id: "routes/innstillinger.applikasjonskategori.($id).rediger";
    page: "/innstillinger/applikasjonskategori/:id?/rediger";
  };
  "routes/innstillinger.applikasjonskategori.$id.slett.tsx": {
    id: "routes/innstillinger.applikasjonskategori.$id.slett";
    page: "/innstillinger/applikasjonskategori/:id/slett";
  };
  "routes/ressurs-admin.opprett-ny-tildeling.tsx": {
    id: "routes/ressurs-admin.opprett-ny-tildeling";
    page: "/ressurs-admin/opprett-ny-tildeling";
  };
  "routes/tjeneste-admin.rediger.ressurs.$id.tsx": {
    id: "routes/tjeneste-admin.rediger.ressurs.$id";
    page: "/tjeneste-admin/rediger/ressurs/:id";
  };
  "routes/tjeneste-admin.ressurser.$id.slett.tsx": {
    id: "routes/tjeneste-admin.ressurser.$id.slett";
    page: "/tjeneste-admin/ressurser/:id/slett";
  };
  "routes/innstillinger.haandhevingstyper.tsx": {
    id: "routes/innstillinger.haandhevingstyper";
    page: "/innstillinger/haandhevingstyper" | "/innstillinger/haandhevingstyper/:id/rediger";
  };
  "routes/innstillinger.haandhevingstyper.$id.rediger.tsx": {
    id: "routes/innstillinger.haandhevingstyper.$id.rediger";
    page: "/innstillinger/haandhevingstyper/:id/rediger";
  };
  "routes/tjeneste-admin.ressurser._index.tsx": {
    id: "routes/tjeneste-admin.ressurser._index";
    page: "/tjeneste-admin/ressurser";
  };
  "routes/ressurs-admin.administrer.$id.tsx": {
    id: "routes/ressurs-admin.administrer.$id";
    page: "/ressurs-admin/administrer/:id";
  };
  "routes/innstillinger.lisensmodeller.tsx": {
    id: "routes/innstillinger.lisensmodeller";
    page: "/innstillinger/lisensmodeller" | "/innstillinger/lisensmodeller/:id?/rediger" | "/innstillinger/lisensmodeller/:id/slett";
  };
  "routes/innstillinger.lisensmodeller.($id).rediger.tsx": {
    id: "routes/innstillinger.lisensmodeller.($id).rediger";
    page: "/innstillinger/lisensmodeller/:id?/rediger";
  };
  "routes/innstillinger.lisensmodeller.$id.slett.tsx": {
    id: "routes/innstillinger.lisensmodeller.$id.slett";
    page: "/innstillinger/lisensmodeller/:id/slett";
  };
  "routes/tjeneste-admin.ressurs.$id.tsx": {
    id: "routes/tjeneste-admin.ressurs.$id";
    page: "/tjeneste-admin/ressurs/:id";
  };
  "routes/innstillinger.brukertyper.tsx": {
    id: "routes/innstillinger.brukertyper";
    page: "/innstillinger/brukertyper" | "/innstillinger/brukertyper/:id/rediger";
  };
  "routes/innstillinger.brukertyper.$id.rediger.tsx": {
    id: "routes/innstillinger.brukertyper.$id.rediger";
    page: "/innstillinger/brukertyper/:id/rediger";
  };
  "routes/ressurs.$id.ny-tildeling.tsx": {
    id: "routes/ressurs.$id.ny-tildeling";
    page: "/ressurs/:id/ny-tildeling" | "/ressurs/:id/ny-tildeling/brukere" | "/ressurs/:id/ny-tildeling/brukere/:userId/org/:orgId/tildel" | "/ressurs/:id/ny-tildeling/grupper" | "/ressurs/:id/ny-tildeling/grupper/:roleId/org/:orgId/tildel";
  };
  "routes/ressurs.$id.ny-tildeling.brukere.tsx": {
    id: "routes/ressurs.$id.ny-tildeling.brukere";
    page: "/ressurs/:id/ny-tildeling/brukere" | "/ressurs/:id/ny-tildeling/brukere/:userId/org/:orgId/tildel";
  };
  "routes/ressurs.$id.ny-tildeling.brukere.$userId.org.$orgId.tildel.tsx": {
    id: "routes/ressurs.$id.ny-tildeling.brukere.$userId.org.$orgId.tildel";
    page: "/ressurs/:id/ny-tildeling/brukere/:userId/org/:orgId/tildel";
  };
  "routes/ressurs.$id.ny-tildeling.grupper.tsx": {
    id: "routes/ressurs.$id.ny-tildeling.grupper";
    page: "/ressurs/:id/ny-tildeling/grupper" | "/ressurs/:id/ny-tildeling/grupper/:roleId/org/:orgId/tildel";
  };
  "routes/ressurs.$id.ny-tildeling.grupper.$roleId.org.$orgId.tildel.tsx": {
    id: "routes/ressurs.$id.ny-tildeling.grupper.$roleId.org.$orgId.tildel";
    page: "/ressurs/:id/ny-tildeling/grupper/:roleId/org/:orgId/tildel";
  };
  "routes/gruppe.$id.ny-tildeling.tsx": {
    id: "routes/gruppe.$id.ny-tildeling";
    page: "/gruppe/:id/ny-tildeling" | "/gruppe/:id/ny-tildeling/ressurs/:resourceId/org/:orgId/tildel";
  };
  "routes/gruppe.$id.ny-tildeling.ressurs.$resourceId.org.$orgId.tildel.tsx": {
    id: "routes/gruppe.$id.ny-tildeling.ressurs.$resourceId.org.$orgId.tildel";
    page: "/gruppe/:id/ny-tildeling/ressurs/:resourceId/org/:orgId/tildel";
  };
  "routes/brukere.$id.org.$orgId.tsx": {
    id: "routes/brukere.$id.org.$orgId";
    page: "/brukere/:id/org/:orgId";
  };
  "routes/innstillinger._index.tsx": {
    id: "routes/innstillinger._index";
    page: "/innstillinger";
  };
  "routes/ressurs-admin._index.tsx": {
    id: "routes/ressurs-admin._index";
    page: "/ressurs-admin";
  };
  "routes/ressurser._index.tsx": {
    id: "routes/ressurser._index";
    page: "/ressurser";
  };
  "routes/brukere._index.tsx": {
    id: "routes/brukere._index";
    page: "/brukere";
  };
  "routes/grupper._index.tsx": {
    id: "routes/grupper._index";
    page: "/grupper";
  };
  "routes/ressurser.$id.tsx": {
    id: "routes/ressurser.$id";
    page: "/ressurser/:id" | "/ressurser/:id/bruker-tildelinger" | "/ressurser/:id/bruker-tildelinger/:assignmentRef/slett" | "/ressurser/:id/gruppe-tildelinger" | "/ressurser/:id/gruppe-tildelinger/:assignmentRef/slett";
  };
  "routes/ressurser.$id.bruker-tildelinger.tsx": {
    id: "routes/ressurser.$id.bruker-tildelinger";
    page: "/ressurser/:id/bruker-tildelinger" | "/ressurser/:id/bruker-tildelinger/:assignmentRef/slett";
  };
  "routes/ressurser.$id.bruker-tildelinger.$assignmentRef.slett.tsx": {
    id: "routes/ressurser.$id.bruker-tildelinger.$assignmentRef.slett";
    page: "/ressurser/:id/bruker-tildelinger/:assignmentRef/slett";
  };
  "routes/ressurser.$id.gruppe-tildelinger.tsx": {
    id: "routes/ressurser.$id.gruppe-tildelinger";
    page: "/ressurser/:id/gruppe-tildelinger" | "/ressurser/:id/gruppe-tildelinger/:assignmentRef/slett";
  };
  "routes/ressurser.$id.gruppe-tildelinger.$assignmentRef.slett.tsx": {
    id: "routes/ressurser.$id.gruppe-tildelinger.$assignmentRef.slett";
    page: "/ressurser/:id/gruppe-tildelinger/:assignmentRef/slett";
  };
  "routes/system-admin.tsx": {
    id: "routes/system-admin";
    page: "/system-admin" | "/system-admin/knytt-rettigheter-til-rolle" | "/system-admin/knytt-rettigheter-til-rolle/:id" | "/system-admin/definer-rolle" | "/system-admin/definer-rolle/:id" | "/system-admin/menystyring" | "/system-admin/menystyring/:id";
  };
  "routes/system-admin.knytt-rettigheter-til-rolle.tsx": {
    id: "routes/system-admin.knytt-rettigheter-til-rolle";
    page: "/system-admin/knytt-rettigheter-til-rolle" | "/system-admin/knytt-rettigheter-til-rolle/:id";
  };
  "routes/system-admin.knytt-rettigheter-til-rolle.$id.tsx": {
    id: "routes/system-admin.knytt-rettigheter-til-rolle.$id";
    page: "/system-admin/knytt-rettigheter-til-rolle/:id";
  };
  "routes/system-admin.definer-rolle.tsx": {
    id: "routes/system-admin.definer-rolle";
    page: "/system-admin/definer-rolle" | "/system-admin/definer-rolle/:id";
  };
  "routes/system-admin.definer-rolle.$id.tsx": {
    id: "routes/system-admin.definer-rolle.$id";
    page: "/system-admin/definer-rolle/:id";
  };
  "routes/system-admin.menystyring.tsx": {
    id: "routes/system-admin.menystyring";
    page: "/system-admin/menystyring" | "/system-admin/menystyring/:id";
  };
  "routes/system-admin.menystyring.$id.tsx": {
    id: "routes/system-admin.menystyring.$id";
    page: "/system-admin/menystyring/:id";
  };
  "routes/grupper.$id.tsx": {
    id: "routes/grupper.$id";
    page: "/grupper/:id" | "/grupper/:id/tildelinger" | "/grupper/:id/tildelinger/:assignmentRef/slett" | "/grupper/:id/medlemmer";
  };
  "routes/grupper.$id.tildelinger.tsx": {
    id: "routes/grupper.$id.tildelinger";
    page: "/grupper/:id/tildelinger" | "/grupper/:id/tildelinger/:assignmentRef/slett";
  };
  "routes/grupper.$id.tildelinger.$assignmentRef.slett.tsx": {
    id: "routes/grupper.$id.tildelinger.$assignmentRef.slett";
    page: "/grupper/:id/tildelinger/:assignmentRef/slett";
  };
  "routes/grupper.$id.medlemmer.tsx": {
    id: "routes/grupper.$id.medlemmer";
    page: "/grupper/:id/medlemmer";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};