apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-frontend
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: fint-kontroll-frontend
    app.kubernetes.io/instance: fint-kontroll-frontend_fintlabs-no
spec:
  port: 3000
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-frontend
  prometheus:
    enabled: true
    port: "3000"
    path: /metrics
  url:
    hostname: kontroll.vigoiks.no
    basePath: /alpha/fintlabs-no
  ingress:
    enabled: true
    middlewares:
      - fint-kontroll-sso
  env: []