name: manual deploy

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Select and environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
      org:
        description: 'Select organisation'
        required: true
        default: 'warning'
        type: choice
        options:
          - fintlabs-no
          - ofk-no
          - bfk-no
          - afk-no
      path:
        description: 'Select path'
        required: true
        default: 'warning'
        type: choice
        options:
          - /beta/fintlabs-no
          - /ofk-no
          - /bfk-no
          - /afk-no
      environment:
        description: 'Select environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - beta
          - api
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER_NAME: ${{ inputs.cluster }}
  ORG: ${{ inputs.org }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node_modules
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/setup-node@v4
        if: steps.node_modules.outputs.cache-hit != 'true'
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci --ignore-scripts
        if: steps.node_modules.outputs.cache-hit != 'true'

  cypress-run:
    needs: install
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_TESTS: true
        with:
          build: npm run build
          start: npm start
          browser: chrome

  build-and-deploy:
    needs: [ install, cypress-run ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - run: BASE_PATH=${{ inputs.path }} npm run build

      # Bygg docker image
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ inputs.org }}-${{ inputs.environment }}
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
            type=raw,value=latest,enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Cache static files
        uses: actions/cache@v4
        with:
          path: |
            ./build
          key: ${{ github.sha }}

      - name: Bake manifests with Kustomize
        uses: azure/k8s-bake@v2
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ steps.environment.outputs.result }}/${{ inputs.org}}'
        id: bake

      - uses: azure/login@v2
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"

      - uses: azure/use-kubelogin@v1.1
        with:
          kubelogin-version: 'v0.0.26'

      - name: Set the target cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: '${{ inputs.cluster }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
          admin: 'true'
          use-kubelogin: 'true'

      - name: Deploy
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build.outputs.tags }}
          namespace: ${{ inputs.org }}
